"""add city connection fields to products

Revision ID: 83b81b1890bc
Revises: 346dc0157840
Create Date: 2026-04-29 21:02:17.563219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b81b1890bc'
down_revision: Union[str, Sequence[str], None] = '346dc0157840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('awin_product_normalized_raw_id_key'), 'awin_product_normalized', type_='unique')
    op.drop_index(op.f('ix_awin_product_normalized_raw_id'), table_name='awin_product_normalized')
    op.create_index(op.f('ix_awin_product_normalized_raw_id'), 'awin_product_normalized', ['raw_id'], unique=True)
    op.create_index(op.f('ix_catalog_brand_controls_id'), 'catalog_brand_controls', ['id'], unique=False)
    op.add_column('products', sa.Column('city_connection_type', sa.String(length=40), nullable=True))
    op.add_column('products', sa.Column('city_connection_location', sa.String(length=160), nullable=True))
    op.add_column('products', sa.Column('city_connection_note', sa.String(length=255), nullable=True))
    op.alter_column('products', 'merchant_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'is_affiliate',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_products_city_connection_type'), 'products', ['city_connection_type'], unique=False)
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_city_connection_type'), table_name='products')
    op.alter_column('products', 'is_affiliate',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'merchant_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('products', 'city_connection_note')
    op.drop_column('products', 'city_connection_location')
    op.drop_column('products', 'city_connection_type')
    op.drop_index(op.f('ix_catalog_brand_controls_id'), table_name='catalog_brand_controls')
    op.drop_index(op.f('ix_awin_product_normalized_raw_id'), table_name='awin_product_normalized')
    op.create_index(op.f('ix_awin_product_normalized_raw_id'), 'awin_product_normalized', ['raw_id'], unique=False)
    op.create_unique_constraint(op.f('awin_product_normalized_raw_id_key'), 'awin_product_normalized', ['raw_id'])
    # ### end Alembic commands ###
