"""create awin product feed raw table

Revision ID: faaabbe445a9
Revises: 
Create Date: 2026-04-07 18:35:00.123972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faaabbe445a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awin_product_feed_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('advertiser_id', sa.String(length=50), nullable=True),
    sa.Column('advertiser_name', sa.String(length=255), nullable=True),
    sa.Column('external_product_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('google_product_category', sa.String(length=500), nullable=True),
    sa.Column('product_type', sa.String(length=500), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('price_raw', sa.String(length=50), nullable=True),
    sa.Column('sale_price_raw', sa.String(length=50), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('aw_deep_link', sa.Text(), nullable=True),
    sa.Column('image_link', sa.Text(), nullable=True),
    sa.Column('additional_image_link', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file', 'external_product_id', name='uq_awin_raw_source_file_external_product_id')
    )
    op.create_index(op.f('ix_awin_product_feed_raw_advertiser_id'), 'awin_product_feed_raw', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_awin_product_feed_raw_availability'), 'awin_product_feed_raw', ['availability'], unique=False)
    op.create_index(op.f('ix_awin_product_feed_raw_id'), 'awin_product_feed_raw', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_awin_product_feed_raw_id'), table_name='awin_product_feed_raw')
    op.drop_index(op.f('ix_awin_product_feed_raw_availability'), table_name='awin_product_feed_raw')
    op.drop_index(op.f('ix_awin_product_feed_raw_advertiser_id'), table_name='awin_product_feed_raw')
    op.drop_table('awin_product_feed_raw')
    # ### end Alembic commands ###
